### ISSUE TITLE
Import Prep Spreadsheet - make it multi-row?

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/dzs-import#1]
I like the export-from-Joomla, reorganize-and-condense on spreadsheet, then import spreadsheet to WordPress process we have begun.  It is for sure helpful and faster.

I will probably have Jasmine work on this while I am on vacation next week (Sat. 8/15 to Fri. 8/21)

I have one idea/request to improve the second part, the organize-and-condense part.

Right now you, to condense, you have to cram all the HTML from multiple Joomla pages into one 'content' field on the spreadsheet.  It can be very hard to put lots of stuff in one field.

Is is possible to make it where there are multiple rows of content, but with no new entry on the 'title' field and have it condense that way.

This is complicated, let me try to say it visually below:

Right now it's this:

TITLE                  -    CONTENT
Your Detroit Zoo  -   page1page2page3page4page5
Purchasing           -  page1page2

It would be super cool and reduce chance of user-error (Jasmine and I) if it was like this.

TITLE                  -   CONTENT
Your Detroit Zoo  -   page1
                                page2
                                page3
                                page4
                                page5
Purchasing           -  page1
                                 page2

Are you following me?  Is this doable?  No big worries if not.  Just trying to eliminate possible errors.

**Comment by brashrebel** [comment]
If these were in separate _columns_ instead of rows it wouldn't be a problem.

**Comment by thisisjoewells** [comment]
So we could do this and it would work?
How might we need to re-think this based on new plan of page and child-page for accordions.  Probably little?

![dzs-content-migrator1](https://cloud.githubusercontent.com/assets/9747248/9236462/079b2502-4113-11e5-806a-5933c3845573.jpg)

**Comment by brashrebel** [comment]
Yep. That would be better than different rows.

**Comment by thisisjoewells** [comment]
We are done here.  The content, however messy, is all migrated now.  Good work!
