### ISSUE TITLE
Can we have a Static Page Taxonomy?

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/dzs-import#2]
I don't know if this is the right repo for this request/issue.

As I start to build out temporary empty static pages, so that I can build the full site navigation and make CJ a happy camper, it gets a bit messy.

On my last website at my last job, the developer did a quick function or something to allow us to make a basic nested category system for static pages.  Then on the back-end UI admins could filter pages by category, which was nice, because we had a few dozen.

We would categorize ours by the top-level pages.  Visit, Events, Animals, Support, Education, About.

It seems like a nice back-end UX feature.  If this was a hack we did with a bunch of downsides, I am open to discuss.

**Comment by brashrebel** [comment]
@joelworsham we should add a hierarchical taxonomy to pages. It could be category or something more descriptive. @thisisjoewells can pick. Type, Section, Topic or whatever. Category as a taxonomy name is good but can make things confusing when so many post types use it.

Also, I'm not sure whether we should make a repo just for that taxonomy or put it in a general functionality plugin or in the functions file. Probably not the latter. Please close this issue when you've created that taxonomy. Thanks.

**Comment by joelworsham** [comment]
Why can't we just use parent->child relationships?

**Comment by brashrebel** [comment]
Joe is asking for a taxonomy mostly for navigating the page listing on the backend if I'm not mistaken. With lots of pages, it is nice to be able to filter them by category. In addition, we may end up having a front end use case for this taxonomy.

**Comment by joelworsham** [comment]
Ah okay. Sure.
