### ISSUE TITLE
Animals - What happened to the ones I already made?  They are gone.

### ISSUE THREAD

**Issue by thisisjoewells** [TheDetroitZoo/dzs-import#3]
I created 8 beautiful real-world sample Animal posts.  They are gone now.  I excluded them from the Joomla export-import so it should not be an overwrite issue.  I hope they are on the database somewhere?  Worst case, perhaps we can make another install and restore from a backup-point from before last week and copy them over.

Let me try to remember the ones I made.  Alas, they were beautiful with completed photos and the works...

Gray Wolf
Kangaroo
Red Panda
Poison Dart Frog
One of the Penguins (forget which)
African Spoonbill
Bald Eagle
King Cobra

**Comment by joelworsham** [comment]
Apologies, I think there was a misunderstanding here. I deleted the posts before the import and then ran the final import.

I didn't realize it was important to preserve the existing animals. Unfortunately they are gone :/ Although they exist via the import with data from the current site.

**Comment by thisisjoewells** [comment]
Bummer.

Bad news is, they don't exist now, I excluded them from Kyle's export from Joomla.  

(except I think I forgot to exclude whichever penguin I did, and it is here now, the rest from the list above are not on site).

Any thoughts on how to get them back, short of manually rebuilding?

**Comment by joelworsham** [comment]
I could re-include them from the export and run it again?

**Comment by thisisjoewells** [comment]
I figured it would take about as long to get the export ready for you or Kyle to import than it would to ask Kyle or you to do it.

So.  I have the XML file with missing animals ready.  I'll toss it in your folder on GoogleDrive - Joel - "6-missing-animals--8-25-15.xml"

@brashrebel , if you had to do any extra work before export, I have tagged the missing animals 'wp-export6-deleted-animals' so can quickly find them.

One of you please let me know when you have got them imported, OR can confirm that XML file will work.  

I want to restore/sync the Failover Site where Kyle and I have been doing export work to the Live Site.  It's a bit out of date now....

**Comment by joelworsham** [comment]
Guess what, I just realized I have those animals on my dev site! Looks like I pulled them down after you created them. I'm going to move those up to the staging site.

**Comment by joelworsham** [comment]
They're baaaaaack

**Comment by joelworsham** [comment]
Although... for some reason the import is being buggy and refuses to import the animal facts... sigh

**Comment by thisisjoewells** [comment]
A few had minor glitches.  Just fixed em' by hand.  We're done here. :pizza:
